### ISSUE TITLE
Defold 1.2.178 dynCall error

### ISSUE THREAD

**Issue by GreenArrow18** [AGulev/jstodef#4]
Hi @AGulev I am getting this error:
Uncaught ReferenceError: dynCall is not defined

It only started after upgrading to the latest 1.2.178 Defold version. Probably related to the Emscripten update?

How can this be fixed?

Thanks!

**Comment by AGulev** [comment]
Thanks for the report, I'll take a look today-tomorrow!

**Comment by AGulev** [comment]
Solved here https://github.com/AGulev/jstodef/releases/tag/1.2.0
