### ISSUE TITLE
/jstodef/src/jstodef.cpp 	Line 82: too few arguments to function call, expected 5, have 3

### ISSUE THREAD

**Issue by ainonovo** [AGulev/jstodef#9]
just add to dependencies
fetch library
and build html5

![1](https://user-images.githubusercontent.com/24792249/218795219-a6be2962-a971-4377-837f-d9b98dedb0a6.png)

[log.zip](https://github.com/AGulev/jstodef/files/10734599/log.zip)

p/s defold 1.3.7

please help

**Comment by AGulev** [comment]
use the latest defold version with the newest extansion version : https://github.com/AGulev/jstodef/archive/refs/tags/2.0.0.zip
or use older version of the extension with Defold 1.3.7 https://github.com/AGulev/jstodef/archive/refs/tags/1.4.0.zip

**Comment by ainonovo** [comment]
Thanks
